### ISSUE TITLE
Caster_qt build issues - release 10.2.2

### ISSUE THREAD

**Issue by lydiazoghbi** [clariusdev/cast#114]
I can't seem to be able to compile the latest caster_qt example. I get an error saying 'QmutexLocker' is not a template (in the display.cpp script). I also get an error saying that memcpy is not a member of std (in caster.cpp ln. 403). I'm working on Ubuntu 20.04, Qt 5.12.8, Python3.8. I tried upgrading to Qt6, but the same error persisted. Any hints on what could be possibly causing this? Thank you!

**Comment by lydiazoghbi** [comment]
Here's a transcript of the error if I try to run make from the terminal in caster_qt directory:
```
display.cpp: In member function ‘void UltrasoundImage::loadImage(const void*, int, int, int, int)’:
display.cpp:46:5: error: ‘QMutexLocker’ is not a template
   46 |     QMutexLocker<QMutex> locker(&lock_);
      |     ^~~~~~~~~~~~
display.cpp: In member function ‘void UltrasoundImage::clearOverlays()’:
display.cpp:266:14: error: ‘class QPainterPath’ has no member named ‘clear’
  266 |     overlay_.clear();
      |              ^~~~~
display.cpp: In member function ‘virtual void UltrasoundImage::resizeEvent(QResizeEvent*)’:
display.cpp:280:5: error: ‘QMutexLocker’ is not a template
  280 |     QMutexLocker<QMutex> locker(&lock_);
      |     ^~~~~~~~~~~~
display.cpp:285:14: error: ‘class QPainterPath’ has no member named ‘clear’
  285 |     overlay_.clear();
      |              ^~~~~
display.cpp: In member function ‘virtual void UltrasoundImage::drawBackground(QPainter*, const QRectF&)’:
display.cpp:351:5: error: ‘QMutexLocker’ is not a template
  351 |     QMutexLocker<QMutex> locker(&lock_);
      |     ^~~~~~~~~~~~
display.cpp: In member function ‘void RfSignal::loadSignal(const void*, int, int, int)’:
display.cpp:415:5: error: ‘QMutexLocker’ is not a template
  415 |     QMutexLocker<QMutex> locker(&lock_);
      |     ^~~~~~~~~~~~
display.cpp: In member function ‘virtual void RfSignal::drawForeground(QPainter*, const QRectF&)’:
display.cpp:476:9: error: ‘QMutexLocker’ is not a template
  476 |         QMutexLocker<QMutex> locker(&lock_);
      |         ^~~~~~~~~~~~
make: *** [Makefile:531: display.o] Error 1
```

**Comment by clariusk** [comment]
you'll want to make sure you update to the Qt6 libraries, you'll see they templated the mutex helper in the latest version:
- https://doc.qt.io/qt-5/qmutexlocker.html 
- https://doc.qt.io/qt-6/qmutexlocker.html

**Comment by lydiazoghbi** [comment]
Thanks! For some reason Qt Creator kept looking for Qt5 on my system. I remove that path and the package compiles, but when I try to launch caster_qt, I get an error message saying:
```
error initializing listener
Segmentation fault (core dumped)
```

**Comment by clariusk** [comment]
please see the release note here: https://github.com/clariusdev/cast/releases, known issue in this version that the init() function returns the wrong value, will be corrected in the next release.

**Comment by lydiazoghbi** [comment]
Beautiful, thank you so much, that was the issue :)
